[package]
name = "aoc2019"
version = "0.1.0"
edition = "2018"

[dev-dependencies]
rstest = "0.4.1"

[dependencies]
itertools = "0.8.2"
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
maplit = "1.0.2"
permutator = "0.3.3"
