name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run release
      run: cargo run --release
    - name: Run tests
      run: cargo test --verbose
